FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    pulseaudio-utils \
    alsa-utils \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir wyoming-satellite

ENTRYPOINT ["python3", "-m", "wyoming_satellite"]
