version: '3.3'

services:
  archimedes-bridge:
    build:
      context: .
      dockerfile: Dockerfile.bridge
    container_name: archimedes-telegram-bridge
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"
