import os

base_path = "/home/pirate/docker/anticitera.deft.work/content"
languages = ["en", "fr", "de", "it", "pt", "el", "ru", "cn", "es"] # Added es just in case, though it wasn't recently generated by script

image_markdown = "\n![European Digital Sovereignty Committee](/img/soberania_digital_comite.png)\n"

# Translation of Alt Text (approximate)
alt_texts = {
    "en": "European Digital Sovereignty Committee",
    "es": "Comité de Soberanía Digital Europea",
    "fr": "Comité de Souveraineté Numérique Européenne",
    "de": "Ausschuss für digitale europäische Souveränität",
    "it": "Comitato per la Sovranità Digitale Europea",
    "pt": "Comité de Soberania Digital Europeia",
    "el": "Επιτροπή Ευρωπαϊκής Ψηφιακής Κυριαρχίας",
    "ru": "Европейский комитет цифрового суверенитета",
    "cn": "欧洲数字主权委员会"
}

for lang in languages:
    # Handle the fact that ES is not in the same folder structure usually? 
    # Wait, es is at content/es/blog? Or content/blog (legacy)?
    # The list_dir earlier showed content/blog/Llamamiento... exists?
    # No, earlier list_dir of content/blog showed "Llamamiento_Soberania_Digital.md"
    # But content/es/blog does not exist? content/es has files directly.
    # Ah, the Spanish file is at /content/blog/Llamamiento_Soberania_Digital.md (root blog).
    # The others are at /content/{lang}/blog/Llamamiento_Soberania_Digital.md
    
    if lang == "es":
         file_path = os.path.join(base_path, "blog", "Llamamiento_Soberania_Digital.md")
    else:
         file_path = os.path.join(base_path, lang, "blog", "Llamamiento_Soberania_Digital.md")

    if not os.path.exists(file_path):
        print(f"Skipping {lang}: file not found at {file_path}")
        continue
        
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Check if image already exists
    if "soberania_digital_comite.png" in content:
        print(f"Skipping {lang}: image already present.")
        continue

    # Insert image after the first H2 header (usually the first substantial header)
    # The first line after frontmatter is usually empty, then ## Header
    
    # We look for the first line starting with "## "
    lines = content.splitlines()
    new_lines = []
    inserted = False
    
    in_frontmatter = False
    frontmatter_count = 0
    
    for line in lines:
        new_lines.append(line)
        
        if line.strip() == "---":
            frontmatter_count += 1
            if frontmatter_count == 2:
                # End of frontmatter
                pass
        
        # If we are past frontmatter and find a header, inject before or after?
        # User said "incluir imagen chula".
        # Let's inject it right after the first H2.
        
        if frontmatter_count >= 2 and line.startswith("## ") and not inserted:
            # Inject image after this header
            alt = alt_texts.get(lang, "European Digital Sovereignty Committee")
            img_tag = f"\n![{alt}](/img/soberania_digital_comite.png)\n"
            new_lines.append(img_tag)
            inserted = True
            
    if not inserted:
        # Fallback: append to end if no header found? Or duplicate?
        # Better: insert at top of body if no header
        pass
        
    with open(file_path, "w", encoding="utf-8") as f:
        f.write("\n".join(new_lines))
    
    print(f"Injected image in {lang}")
